/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumni_202457201064;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author siti novi triana
 */
public class PanelGuru extends javax.swing.JPanel {
     DefaultTableModel model;
    int rowSelected =  -1;

    /**
     * Creates new form PanelGuru
     */
    public PanelGuru() {
        initComponents();
        reset();
        load_tabel_guru();
}
        void reset(){
        //kosongkan isi text field kode jurusan
        tNIP1.setText(null);
        // aktifkan kembali text field kode jurusan agar bisa diedit 
        tNIP1.setEditable(true);
        //kosongkan isi text field nama jurusan
        tNamaGuru1.setText(null);
        cbJenisKelamin1.setSelectedItem(null);
        tAlamat1.setText(null);
    }
        void load_tabel_guru(){
        //membuat objek model tabel baru
        DefaultTableModel model = new DefaultTableModel();
        //menambahkan kolom kedalam model tabel
        //kolom pertama untuk kode jurusan
        model.addColumn("NIP");
        //kolom kedua untuk nama jurusan
        model.addColumn("Nama Guru");
        model.addColumn("L/P");
        model.addColumn("Alamat");
       
        
        //query SQL untuk mengambil semua data dari table jurusan
        String sql = "SELECT * FROM guru";
        
            try {
                //membuka koneksi kedatabase
                Connection conn = koneksi.konek();

                //membuka statement untuk menjalankan array
                Statement st = conn.createStatement();

                //menjalankan query dan menyimpan hasilnya dalam ResultSet
                ResultSet rs = st.executeQuery(sql);

                //melakukan iterasi untuk setiap baris data hasil query
                while (rs.next()) {
                    //mengambil data kolom nip
                    String nip = rs.getString("nip");

                    //mengambil data kolom nama_guru
                    String namaGuru = rs.getString("nama_guru");
                    
                    //mengambil data kolom jeniskelamin
                    String jenisKelamin = rs.getString("gender");
                    
                    //mengambil data alamat
                    String alamat = rs.getString("alamat");
                    
 

                    //membuat array berisi data satu baris
                    Object[] baris = {nip, namaGuru, jenisKelamin, alamat};

                    //menambahkan array baris kedalam model table
                    model.addRow(baris);

                }
            } catch (SQLException sQLException) {
            //menampilkan pesan error jika gagal mengambil data dari database
            JOptionPane.showMessageDialog(null, "Gagal Mengambil Data!");
            }

            //menampilkan model yang sudah diisi kedalam tabel GUI
            TableGuru1.setModel(model);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelIsi = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        bTutup = new javax.swing.JButton();
        tNamaGuru1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableGuru1 = new javax.swing.JTable();
        cbJenisKelamin1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        tAlamat1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bUbah1 = new javax.swing.JButton();
        bTambah1 = new javax.swing.JButton();
        bHapus1 = new javax.swing.JButton();
        bReset1 = new javax.swing.JButton();
        tNIP1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Data Guru");

        bTutup.setBackground(new java.awt.Color(51, 255, 51));
        bTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201064/gambar/icons8-close-20.png"))); // NOI18N
        bTutup.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(bTutup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tNamaGuru1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaGuru1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("Alamat");

        TableGuru1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIP", "Nama", "Jenis Kelamin", "Alamat"
            }
        ));
        TableGuru1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableGuru1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableGuru1);

        cbJenisKelamin1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki Laki", "Perempuan", " " }));
        cbJenisKelamin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisKelamin1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("Jenis Kelamin");

        tAlamat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAlamat1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setText("NIP");

        bUbah1.setBackground(new java.awt.Color(255, 153, 51));
        bUbah1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bUbah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201064/gambar/icons8-note-20.png"))); // NOI18N
        bUbah1.setText("Ubah");
        bUbah1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bUbah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbah1ActionPerformed(evt);
            }
        });

        bTambah1.setBackground(new java.awt.Color(0, 204, 51));
        bTambah1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bTambah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201064/gambar/icons8-plus-20.png"))); // NOI18N
        bTambah1.setText("Tambah");
        bTambah1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambah1ActionPerformed(evt);
            }
        });

        bHapus1.setBackground(new java.awt.Color(255, 51, 51));
        bHapus1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bHapus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201064/gambar/icons8-delete-20.png"))); // NOI18N
        bHapus1.setText("Hapus");
        bHapus1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapus1ActionPerformed(evt);
            }
        });

        bReset1.setBackground(new java.awt.Color(0, 102, 255));
        bReset1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bReset1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201064/gambar/icons8-reset-20 (1).png"))); // NOI18N
        bReset1.setText("Reset");
        bReset1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReset1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel14.setText("Nama");

        javax.swing.GroupLayout PanelIsiLayout = new javax.swing.GroupLayout(PanelIsi);
        PanelIsi.setLayout(PanelIsiLayout);
        PanelIsiLayout.setHorizontalGroup(
            PanelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIsiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addComponent(tNamaGuru1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tAlamat1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbJenisKelamin1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tNIP1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelIsiLayout.createSequentialGroup()
                .addGroup(PanelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelIsiLayout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(bTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(bUbah1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(bHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(bReset1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
            .addGroup(PanelIsiLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelIsiLayout.setVerticalGroup(
            PanelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIsiLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIsiLayout.createSequentialGroup()
                        .addComponent(tNIP1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNamaGuru1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbJenisKelamin1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tAlamat1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addGroup(PanelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bTambah1)
                            .addComponent(bUbah1)
                            .addComponent(bHapus1)
                            .addComponent(bReset1)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelIsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(PanelIsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(813, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tNamaGuru1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaGuru1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaGuru1ActionPerformed

    private void cbJenisKelamin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisKelamin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJenisKelamin1ActionPerformed

    private void tAlamat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAlamat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tAlamat1ActionPerformed

    private void bUbah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbah1ActionPerformed
        // TODO add your handling code here:
         
            String NIP = tNIP1.getText();
            String NamaGuru = tNamaGuru1.getText();
            String jeniskelamin= cbJenisKelamin1.getSelectedItem().toString();
            String alamat = tAlamat1.getText();
            //menyiapkan variabel untuk menyimpan singkatan jenis kelami 'L' atau 'P'
            String jk = null;
            //mengubah nilai jenis kelamin dari label menjadi format singkatan yang disimpan di database
           switch (jeniskelamin){
               case "Laki - laki":
                   jk= "L";
                   break;
                   case "Perempuan":
                       jk = "P";
                   break;
                   default:
                       jk=null;
                       break;
           }
            //query SQL untuk mengubah data pada table 
            String sql = "UPDATE guru SET nama_guru=?, gender=?, alamat=? WHERE nip=?";
            
            try {
            //query SQL untuk menyisipkan data ketable jurusan
            Connection conn = koneksi.konek();

            //siapkan query SQL untuk dieksekusi dengan parameter
            PreparedStatement ps = conn.prepareStatement(sql);

            //isi  parameter pertama (?) dengan kode Jurusan
            ps.setString(1, NamaGuru);
            //isi  parameter pertama (?) dengan nama Jurusan
            ps.setString(2, jk);
            ps.setString(3, alamat);
            ps.setString(4, NIP);

            //jalankan query untuk menyimpan data ke databse
            ps.execute();
            //tampilkan pesan bahwa data berhasil disimpan
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan!");
            
        } catch (SQLException sQLException) {
        //jika terjadi kesalahan saat menyimpan data, tampilkan pesan gagal
        JOptionPane.showMessageDialog(null, "Data Gagal Disimpan!");
        }
            //panggil method untuk memuat ulang data pada table jurusan
           load_tabel_guru();
           //panggil method untuk mereset atau mengosongkan inputan
           reset();
    }//GEN-LAST:event_bUbah1ActionPerformed

    private void bTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambah1ActionPerformed
        // TODO add your handling code here:
            String NIP = tNIP1.getText();
            String NamaGuru = tNamaGuru1.getText();
            String alamat = tAlamat1.getText();
            String jeniskelamin= cbJenisKelamin1.getSelectedItem().toString();
            String jk = null;
            //mengubah nilai jenis kelamin dari label menjadi format singkatan yang disimpan di database
           switch (jeniskelamin){
               case "Laki - laki":
                   jk= "L";
                   break;
                   case "Perempuan":
                       jk = "P";
                   break;
                   default:
                       jk=null;
                       break;
           }

            //query SQL untuk mengubah data pada table 
            String sql = "INSERT INTO guru(nip, nama_guru, gender, alamat) VALUES (?,?,?,?)";
            
           try {
            //query SQL untuk menyisipkan data ketable jurusan
            Connection conn = koneksi.konek();

            //siapkan query SQL untuk dieksekusi dengan parameter
            PreparedStatement ps = conn.prepareStatement(sql);

            //isi  parameter pertama (?) dengan kode Jurusan
            ps.setString(1, NIP);
            //isi  parameter pertama (?) dengan nama Jurusan
            ps.setString(2, NamaGuru);
            ps.setString(3, jk);
            ps.setString(4, alamat);
          
            //jalankan query untuk menyimpan data ke databse
            ps.execute();
            //tampilkan pesan bahwa data berhasil disimpan
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan!");
            
         } catch (SQLException sQLException) {
        //jika terjadi kesalahan saat menyimpan data, tampilkan pesan gagal
             JOptionPane.showMessageDialog(null, "Data Gagal Disimpan!");
               System.out.println(sQLException);
        }
            //panggil method untuk memuat ulang data pada table jurusan
           load_tabel_guru();
           //panggil method untuk mereset atau mengosongkan inputan
           reset();
    }//GEN-LAST:event_bTambah1ActionPerformed

    private void bHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapus1ActionPerformed
        // TODO add your handling code here:
         String NIP = tNIP1.getText();
            //query SQL untuk mengubah data pada table 
            String sql = "DELETE FROM guru WHERE nip=?";
            
            try {
            //query SQL untuk menyisipkan data ketable jurusan
            Connection conn = koneksi.konek();

            //siapkan query SQL untuk dieksekusi dengan parameter
            PreparedStatement ps = conn.prepareStatement(sql);

            //isi  parameter pertama (?) dengan kode Jurusan
            ps.setString(1, NIP);
            
            //jalankan query untuk menyimpan data ke databse
            ps.execute();
            //tampilkan pesan bahwa data berhasil disimpan
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan!");
            
        } catch (SQLException sQLException) {
        //jika terjadi kesalahan saat menyimpan data, tampilkan pesan gagal
        JOptionPane.showMessageDialog(null, "Data Gagal Disimpan!");
                System.out.println(sQLException);
        }
            //panggil method untuk memuat ulang data pada table jurusan
           load_tabel_guru();
           //panggil method untuk mereset atau mengosongkan inputan
           reset();
                                         
    }//GEN-LAST:event_bHapus1ActionPerformed

    private void bReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReset1ActionPerformed
        // TODO add your handling code here:
       reset();
    }//GEN-LAST:event_bReset1ActionPerformed

    private void bTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTutupActionPerformed
        // TODO add your handling code here:
        PanelIsi.setVisible(false);
    }//GEN-LAST:event_bTutupActionPerformed

    private void TableGuru1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableGuru1MouseClicked
        // TODO add your handling code here:
         //ambil indeks baris yang diklik oleh pengguna di table TableJurusan1
         int barisYangDipilih = TableGuru1.rowAtPoint(evt.getPoint());
          //ambil indeks baris yang diklik oleh pengguna di table TableJurusan1
         String NIP = TableGuru1.getValueAt(barisYangDipilih, 0).toString();
          //ambil indeks baris yang diklik oleh pengguna di table TableJurusan1
         String namaGuru = TableGuru1.getValueAt(barisYangDipilih, 1).toString();
         String jnsklmn = TableGuru1.getValueAt(barisYangDipilih, 2).toString();
         String alamat = TableGuru1.getValueAt(barisYangDipilih, 3).toString();
         
         //tampilkan kode jurusan di text field tKodeJurusan1
         tNIP1.setText(NIP);
         //nonaktifkan pengeditan pada text field kode jurusan (agar tidak bisa diubah)
         tNIP1.setEditable(false);
         //Tampilkan nama jurusan di text field 
         tNamaGuru1.setText(namaGuru);
         tAlamat1.setText(alamat);
         //mengecek nilai jenis kelamin  dan menyesuaikan pilihan pada combo box cbjeniskelamin1
        switch (jnsklmn) {
            //jika nilai jenis kelamin "L", set pilihan combo box ke "Laki laki" 
            case "L":
                cbJenisKelamin1.setSelectedItem("Laki - laki");
                break;
                
                  //jika nilai jenis kelamin "L", set pilihan combo box ke "Laki laki" 
            case "P":
                cbJenisKelamin1.setSelectedItem("Perempuan");
                break;
                //jika nilainya bukan L atau P, kosongkan pilihan combo box
            default:
              cbJenisKelamin1.setSelectedItem(null);
              break;
        }
 
        
    }//GEN-LAST:event_TableGuru1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelIsi;
    private javax.swing.JTable TableGuru1;
    private javax.swing.JButton bHapus1;
    private javax.swing.JButton bReset1;
    private javax.swing.JButton bTambah1;
    private javax.swing.JButton bTutup;
    private javax.swing.JButton bUbah1;
    private javax.swing.JComboBox<String> cbJenisKelamin1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField tAlamat1;
    private javax.swing.JTextField tNIP1;
    private javax.swing.JTextField tNamaGuru1;
    // End of variables declaration//GEN-END:variables

    private void resetForm() {
    tNIP1.setText("");
    tNamaGuru1.setText("");
    TableGuru1.clearSelection();
    cbJenisKelamin1.setSelectedIndex(0);
    tAlamat1.setText("");
    }
}
