/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumni_202457201064;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author siti novi triana
 */
public class PanelJurusan extends javax.swing.JPanel {
 DefaultTableModel model;
    int rowSelected =  -1;
    /**
     * Creates new form PanelJurusan
     */
    public PanelJurusan() {
        initComponents();
        reset();
        load_tabel_jurusan();
}
        void reset(){
        //kosongkan isi text field kode jurusan
        tKodeJurusan1.setText(null);
        // aktifkan kembali text field kode jurusan agar bisa diedit 
        tKodeJurusan1.setEditable(true);
        //kosongkan isi text field nama jurusan
        tNamaJurusan1.setText(null);
    }
        void load_tabel_jurusan(){
        //membuat objek model tabel baru
        DefaultTableModel model = new DefaultTableModel();
        //menambahkan kolom kedalam model tabel
        //kolom pertama untuk kode jurusan
        model.addColumn("Kode Jurusan");
        //kolom kedua untuk nama jurusan
        model.addColumn("Nama Jurusan");
        
        //query SQL untuk mengambil semua data dari table jurusan
        String sql = "SELECT * FROM jurusan";
        
            try {
                //membuka koneksi kedatabase
                Connection conn = koneksi.konek();

                //membuka statement untuk menjalankan array
                Statement st = conn.createStatement();

                //menjalankan query dan menyimpan hasilnya dalam ResultSet
                ResultSet rs = st.executeQuery(sql);

                //melakukan iterasi untuk setiap baris data hasil query
                while (rs.next()) {
                    //mengambil data kolom kode_jur
                    String kodeJurusan = rs.getString("kode_jur");

                    //mengambil data kolom nama_jurusan
                    String namaJurusan = rs.getString("nama_jurusan");

                    //membuat array berisi data satu baris
                    Object[] baris = {kodeJurusan, namaJurusan};

                    //menambahkan array baris kedalam model table
                    model.addRow(baris);

                }
            } catch (SQLException sQLException) {
            //menampilkan pesan error jika gagal mengambil data dari database
            JOptionPane.showMessageDialog(null, "Gagal Mengambil Data!");
            }

            //menampilkan model yang sudah diisi kedalam tabel GUI
            TableJurusan1.setModel(model);
        }
    
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelIsi = new javax.swing.JPanel();
        bHapus1 = new javax.swing.JButton();
        bReset1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        bTambah1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tKodeJurusan1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tNamaJurusan1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        bTutup1 = new javax.swing.JButton();
        bUbah1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableJurusan1 = new javax.swing.JTable();

        bHapus1.setBackground(new java.awt.Color(255, 51, 51));
        bHapus1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bHapus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201064/gambar/icons8-delete-20.png"))); // NOI18N
        bHapus1.setText("Hapus");
        bHapus1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapus1ActionPerformed(evt);
            }
        });

        bReset1.setBackground(new java.awt.Color(0, 102, 255));
        bReset1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bReset1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201064/gambar/icons8-reset-20 (1).png"))); // NOI18N
        bReset1.setText("Reset");
        bReset1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReset1ActionPerformed(evt);
            }
        });

        bTambah1.setBackground(new java.awt.Color(0, 204, 51));
        bTambah1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bTambah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201064/gambar/icons8-plus-20.png"))); // NOI18N
        bTambah1.setText("Tambah");
        bTambah1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambah1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Kode Jurusan");

        tKodeJurusan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKodeJurusan1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Nama Jurusan");

        tNamaJurusan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaJurusan1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Data Jurusan");

        bTutup1.setBackground(new java.awt.Color(102, 255, 102));
        bTutup1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201064/gambar/icons8-close-20.png"))); // NOI18N
        bTutup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTutup1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 358, Short.MAX_VALUE)
                .addComponent(bTutup1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(bTutup1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bUbah1.setBackground(new java.awt.Color(255, 153, 51));
        bUbah1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bUbah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201064/gambar/icons8-note-20.png"))); // NOI18N
        bUbah1.setText("Ubah");
        bUbah1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bUbah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbah1ActionPerformed(evt);
            }
        });

        TableJurusan1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Kode Jurusan", "Nama Jurusan"
            }
        ));
        TableJurusan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableJurusan1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableJurusan1);

        javax.swing.GroupLayout PanelIsiLayout = new javax.swing.GroupLayout(PanelIsi);
        PanelIsi.setLayout(PanelIsiLayout);
        PanelIsiLayout.setHorizontalGroup(
            PanelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIsiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelIsiLayout.createSequentialGroup()
                        .addGroup(PanelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tKodeJurusan1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelIsiLayout.createSequentialGroup()
                                .addComponent(bTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(bUbah1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(PanelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelIsiLayout.createSequentialGroup()
                                .addComponent(bHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(bReset1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tNamaJurusan1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelIsiLayout.createSequentialGroup()
                .addGroup(PanelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 39, Short.MAX_VALUE))
        );
        PanelIsiLayout.setVerticalGroup(
            PanelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIsiLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(17, 17, 17)
                .addGroup(PanelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNamaJurusan1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tKodeJurusan1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(PanelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTambah1)
                    .addComponent(bUbah1)
                    .addComponent(bHapus1)
                    .addComponent(bReset1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PanelIsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PanelIsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapus1ActionPerformed
        // TODO add your handling code here:
         //ambil input dari text field tKodeJurusan1 dan disimpan ke variable kodeJurusan
            String kodeJurusan = tKodeJurusan1.getText();
            //query SQL untuk mengubah data pada table 
            String sql = "DELETE FROM jurusan WHERE kode_jur=?";
            
            try {
            //query SQL untuk menyisipkan data ketable jurusan
            Connection conn = koneksi.konek();

            //siapkan query SQL untuk dieksekusi dengan parameter
            PreparedStatement ps = conn.prepareStatement(sql);

            //isi  parameter pertama (?) dengan kode Jurusan
            ps.setString(1, kodeJurusan);
            
            //jalankan query untuk menyimpan data ke databse
            ps.execute();
            //tampilkan pesan bahwa data berhasil disimpan
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan!");
            
        } catch (SQLException sQLException) {
        //jika terjadi kesalahan saat menyimpan data, tampilkan pesan gagal
        JOptionPane.showMessageDialog(null, "Data Gagal Disimpan!");
                System.out.println(sQLException);
        }
            //panggil method untuk memuat ulang data pada table jurusan
           load_tabel_jurusan();
           //panggil method untuk mereset atau mengosongkan inputan
           reset();
    }//GEN-LAST:event_bHapus1ActionPerformed

    private void bReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReset1ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_bReset1ActionPerformed

    private void bTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambah1ActionPerformed
        // TODO add your handling code here:
            //ambil input dari text field tKodeJurusan1 dan disimpan ke variable kodeJurusan
            String kodeJurusan = tKodeJurusan1.getText();
            //ambil input dari text field tNamaJurusan1 dan disimpan ke variable namaJurusan
            String namaJurusan = tNamaJurusan1.getText();
            
            //query SQL untuk mengubah data pada table 
            String sql = "INSERT INTO jurusan(kode_jur, nama_jurusan) VALUES (?,?)";
            
           try {
            //query SQL untuk menyisipkan data ketable jurusan
            Connection conn = koneksi.konek();

            //siapkan query SQL untuk dieksekusi dengan parameter
            PreparedStatement ps = conn.prepareStatement(sql);

            //isi  parameter pertama (?) dengan kode Jurusan
            ps.setString(1, kodeJurusan);
            //isi  parameter pertama (?) dengan nama Jurusan
            ps.setString(2, namaJurusan);

            //jalankan query untuk menyimpan data ke databse
            ps.execute();
            //tampilkan pesan bahwa data berhasil disimpan
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan!");
            
         } catch (SQLException sQLException) {
        //jika terjadi kesalahan saat menyimpan data, tampilkan pesan gagal
             JOptionPane.showMessageDialog(null, "Data Gagal Disimpan!");
               System.out.println(sQLException);
        }
            //panggil method untuk memuat ulang data pada table jurusan
           load_tabel_jurusan();
           //panggil method untuk mereset atau mengosongkan inputan
           reset();
    }//GEN-LAST:event_bTambah1ActionPerformed

   
    private void tKodeJurusan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKodeJurusan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tKodeJurusan1ActionPerformed

    private void tNamaJurusan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaJurusan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaJurusan1ActionPerformed

    private void bUbah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbah1ActionPerformed
        // TODO add your handling code here:
          //ambil input dari text field tKodeJurusan1 dan disimpan ke variable kodeJurusan
            String kodeJurusan = tKodeJurusan1.getText();
            //ambil input dari text field tNamaJurusan1 dan disimpan ke variable namaJurusan
            String namaJurusan = tNamaJurusan1.getText();
            
            //query SQL untuk mengubah data pada table 
            String sql = "UPDATE jurusan SET nama_jurusan=? WHERE kode_jur=?";
            
            try {
            //query SQL untuk menyisipkan data ketable jurusan
            Connection conn = koneksi.konek();

            //siapkan query SQL untuk dieksekusi dengan parameter
            PreparedStatement ps = conn.prepareStatement(sql);

            //isi  parameter pertama (?) dengan kode Jurusan
            ps.setString(1, namaJurusan);
            //isi  parameter pertama (?) dengan nama Jurusan
            ps.setString(2, kodeJurusan);

            //jalankan query untuk menyimpan data ke databse
            ps.execute();
            //tampilkan pesan bahwa data berhasil disimpan
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan!");
            
        } catch (SQLException sQLException) {
        //jika terjadi kesalahan saat menyimpan data, tampilkan pesan gagal
        JOptionPane.showMessageDialog(null, "Data Gagal Disimpan!");
                System.out.println(sQLException);
        }
            //panggil method untuk memuat ulang data pada table jurusan
           load_tabel_jurusan();
           //panggil method untuk mereset atau mengosongkan inputan
           reset();
    }//GEN-LAST:event_bUbah1ActionPerformed

    private void bTutup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTutup1ActionPerformed
        // TODO add your handling code here:
        PanelIsi.setVisible(false);
    }//GEN-LAST:event_bTutup1ActionPerformed

    private void TableJurusan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableJurusan1MouseClicked
        // TODO add your handling code here:
        //ambil indeks baris yang diklik oleh pengguna di table TableJurusan1
         int barisYangDipilih = TableJurusan1.rowAtPoint(evt.getPoint());
          //ambil indeks baris yang diklik oleh pengguna di table TableJurusan1
         String kodeJurusan = TableJurusan1.getValueAt(barisYangDipilih, 0).toString();
          //ambil indeks baris yang diklik oleh pengguna di table TableJurusan1
         String namaJurusan = TableJurusan1.getValueAt(barisYangDipilih, 1).toString();
         
         //tampilkan kode jurusan di text field tKodeJurusan1
         tKodeJurusan1.setText(kodeJurusan);
         //nonaktifkan pengeditan pada text field kode jurusan (agar tidak bisa diubah)
         tKodeJurusan1.setEditable(false);
         //Tampilkan nama jurusan di text field 
         tNamaJurusan1.setText(namaJurusan);
        
    }//GEN-LAST:event_TableJurusan1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelIsi;
    private javax.swing.JTable TableJurusan1;
    private javax.swing.JButton bHapus1;
    private javax.swing.JButton bReset1;
    private javax.swing.JButton bTambah1;
    private javax.swing.JButton bTutup1;
    private javax.swing.JButton bUbah1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField tKodeJurusan1;
    private javax.swing.JTextField tNamaJurusan1;
    // End of variables declaration//GEN-END:variables

    private void resetForm(){
    tKodeJurusan1.setText("");
    tNamaJurusan1.setText("");
    TableJurusan1.clearSelection();
    }
}
